setSignatures = ((list([0])),
                 (list([1])),
                 (list([1, 1]), list([2])),
                 (list([1, 1, 1]), list([1, 2]), list([3])),
                 (list([1, 1, 1, 1]), list([1, 1, 2]), list([2, 2]), list([1, 3]), list([4])),
                 (list([1, 1, 1, 1, 1]), list([1, 1, 1, 2]), list([1, 1, 3]), list([1, 4]), list([1, 2, 2]),
                  list([2, 3]), list([5])),
                 (list([1, 1, 1, 1, 1, 1]), list([1, 1, 1, 1, 2]), list([1, 1, 1, 3]), list([1, 1, 2, 2]),
                  list([1, 1, 4]), list([1, 2, 3]), list([1, 5]), list([2, 2, 2]), list([2, 4]), list([3, 3]),
                  list([6])),
                 )


AA_three_to_one = {
    'ALA': 'A',
    'ARG': 'R',
    'ASN': 'N',
    'ASP': 'D',
    'CYS': 'C',
    'GLU': 'E',
    'GLN': 'Q',
    'GLY': 'G',
    'HIS': 'H',
    'ILE': 'I',
    'LEU': 'L',
    'LYS': 'K',
    'MET': 'M',
    'PHE': 'F',
    'PRO': 'P',
    'SER': 'S',
    'THR': 'T',
    'TRP': 'W',
    'TYR': 'Y',
    'VAL': 'V',
}
